"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import useReducedMotion from "@/hooks/useMotionPreference";
import { ArrowUpRight } from "lucide-react";
import MagneticLink from "./MagneticLink";

export default function Footer() {
  const reduced = useReducedMotion();
  return <footer id="footer" className="immersive-footer"><div className="footer-invitation"><span className="eyebrow-light"><span className="signal-dot" /> NEXT / YOUR PROJECT</span><div><motion.h2 initial={reduced ? false : { y: 50, opacity: 0 }} whileInView={{ y: 0, opacity: 1 }} viewport={{ once: true }} transition={{ duration: .8 }}>Make an<br /><em>impression.</em></motion.h2><MagneticLink href="/quote" className="footer-project-orb" aria-label="Start a project with MAS LED"><ArrowUpRight size={50} strokeWidth={1.2} /><span>LET&apos;S BUILD<br />SOMETHING GREAT</span></MagneticLink></div><p>Big ideas deserve a bigger canvas.<br />Tell us what you have in mind.</p></div><div className="footer-details"><div className="footer-contact"><span className="eyebrow-light">START A CONVERSATION</span><a href="mailto:info@masled.in">info@masled.in <ArrowUpRight size={18} /></a><a href="tel:+918743888577">+91 87438 88577</a><p>Mastech Advertising Solutions Pvt Ltd<br />1st Floor, Wegmans Business Park, Plot No 3,<br />Knowledge Park-3, Greater Noida, UP-201306</p></div><div className="footer-nav-column"><span className="eyebrow-light">EXPLORE</span>{[{ name: "The range", href: "/products" }, { name: "Experiences", href: "/#experience" }, { name: "About MAS", href: "/about" }, { name: "Contact", href: "/contact" }].map(link => <Link key={link.name} href={link.href}>{link.name}</Link>)}</div><div className="footer-nav-column"><span className="eyebrow-light">INFORMATION</span>{[{ name: "Support", href: "/support" }, { name: "Warranty", href: "/warranty" }, { name: "Privacy", href: "/privacy" }, { name: "Terms", href: "/terms" }].map(link => <Link key={link.name} href={link.href}>{link.name}</Link>)}</div><div className="footer-location"><span className="eyebrow-light">BASED IN INDIA.<br />BUILT FOR YOUR WORLD.</span><span className="footer-compass" aria-hidden="true"><ArrowUpRight size={56} strokeWidth={.8} /></span></div></div><div className="footer-wordmark" aria-hidden="true">MAS LED<span>®</span></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Mastech Advertising Solutions Pvt Ltd</span><span>LIGHT WITHOUT LIMITS.</span><a href="#top" onClick={event => { event.preventDefault(); window.scrollTo({ top: 0, behavior: reduced ? "instant" : "smooth" }); }}>BACK TO TOP ↑</a></div></footer>;
}
